### ISSUE TITLE
v8-profiler问题

### ISSUE THREAD

**Issue by allenlikeu** [NetEase/pomelo-admin-web#1]
在app.js中增加 app.enable('systemMonitor');
在启动时，发现一个错误信息 Cannot find module 'v8-profiler'.

在npm install v8-profiler时，出现如下错误：

gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd E:\practise\chatServer\game-server\node_modules\pomelo\node_modules
\v8-profiler
gyp ERR! node -v v0.8.9
gyp ERR! node-gyp -v v0.6.8
gyp ERR! not ok
npm ERR! v8-profiler@3.6.2-1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the v8-profiler@3.6.2-1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "v8-profiler"
npm ERR! cwd E:\practise\chatServer\game-server\node_modules\pomelo\node_modules

npm ERR! node -v v0.8.9
npm ERR! npm -v 1.1.61
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\practise\chatServer\game-server\node_modules\pomelo\node_modules
\npm-debug.log
npm ERR! not ok code 0

小弟的环境是  win 7.  请问如何安装？

若windows环境下不支持v8-profiler的安装，那如何使用pomelo-admin-web。

另外发现onlineUser这个模块也找不到，需要自己定制么？

**Comment by py8765** [comment]
windows环境是不支持v8-profiler的。

**Comment by allenlikeu** [comment]
既然不支持，那么请问，如何使用pomelo-admin-web呢？

**Comment by changchang** [comment]
对于不支持的环境下，pomelo-admin-web对应的页面不可用。在下一版本会对web升级，只呈现支持的管理页面。

**Comment by allenlikeu** [comment]
目前的情况是这样的，在game-server的 app.js中，添加 app.enable('v8-profiler')之后，启动过程中就报错，打开所有页面，均不正常。。。
这个。。不会是都不支持吧？那悲催了。。。

**Comment by piaohai** [comment]
app.enable('systemMonitor'); 就可以了，不需要具体到模块。只是管理界面上那个PROFILER打不开。
