### ISSUE TITLE
app.configure is not a function

### ISSUE THREAD

**Issue by ZYanXiang** [NetEase/pomelo-admin-web#13]
使用的时候遇到了这个问题：
app.configure(function() {
    ^

TypeError: app.configure is not a function
    at Object.<anonymous> (/home/zyx/treasures/pomelo-admin-web/app.js:10:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

请问有人知道问什么吗，怎么改呢？

**Comment by stevendaye** [comment]
app.configure 完全被删除 express from v4
